# Generated by Django 4.2.5 on 2023-09-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
